// Master category taxonomy with suggested elements per category
// This is the single source of truth for all category names across the platform

export const MASTER_CATEGORIES = [
  'Production & Fabrication',
  'Stage',
  'Branding & Signage',
  'Sound',
  'Lighting',
  'Video & LED',
  'Manpower',
  'Furniture',
  'Venue & Infrastructure',
  'Power & Electrical',
  'Venue Booking',
  'Food & Beverage',
  'Travel Booking',
  'Logistics',
  'Permissions & Legal',
  'Insurance',
  'Technology & IT',
  'Gifts & Merchandise',
  'Photography & Videography',
  'Agency Cost',
  'Miscellaneous',
]

// Suggested elements per category — user can pick, delete, or add their own
export const CATEGORY_SUGGESTIONS = {
  'Production & Fabrication': [
    { element_name: 'Arch Gate', finish: 'MS frame with flex facia' },
    { element_name: 'Registration Backdrop', finish: 'Flex print with MS frame' },
    { element_name: 'Closing Panels', finish: 'Flex finish, MS frame' },
    { element_name: 'Side Masking Panels', finish: 'Flex finish, MS frame' },
    { element_name: 'Photo Ops Backdrop', finish: 'Step-repeat or custom print' },
    { element_name: 'Ceiling Treatment', finish: 'Fabric draping' },
    { element_name: 'Photo Booth', finish: 'Custom fabricated structure' },
    { element_name: 'Standees', finish: 'Flex print with stand' },
    { element_name: 'Entrance Gate', finish: 'Custom fabrication' },
    { element_name: 'Counter / Kiosk', finish: 'Laminated finish' },
  ],
  'Stage': [
    { element_name: 'Main Stage', finish: 'Wooden platform with carpet finish' },
    { element_name: 'Stage Extension', finish: 'Matching finish to main stage' },
    { element_name: 'Podium', finish: 'Laminated wood finish' },
    { element_name: 'Lectern', finish: 'Branded / plain' },
    { element_name: 'Riser / Steps', finish: 'Carpeted wooden riser' },
    { element_name: 'Stage Skirting', finish: 'Pleated fabric or flex' },
    { element_name: 'Stage Carpet', finish: 'Red / custom colour' },
    { element_name: 'Stage Backdrop', finish: 'Flex print or fabric' },
    { element_name: 'Wings / Side Panels', finish: 'Masking panels' },
    { element_name: 'Green Room Setup', finish: '' },
  ],
  'Branding & Signage': [
    { element_name: 'Event Logo / Branding', finish: 'Digital print' },
    { element_name: 'Directional Signage', finish: 'Flex print' },
    { element_name: 'Welcome Banner', finish: 'Vinyl print' },
    { element_name: 'Table Cards / Nameplates', finish: 'Printed cards' },
    { element_name: 'Roll-up Banners', finish: 'Retractable, flex print' },
    { element_name: 'Photo Ops Backdrop', finish: 'Step-repeat or custom print' },
    { element_name: 'Vehicle Branding', finish: 'Vinyl wrap' },
  ],
  'Sound': [
    { element_name: 'Main Sound System', finish: 'Line array, as per pax capacity' },
    { element_name: 'Microphones', finish: 'Wireless handheld + lapel' },
    { element_name: 'Stage Monitors', finish: 'Wedge monitors' },
    { element_name: 'Audio Mixing Console', finish: 'Digital mixer' },
    { element_name: 'Amplifiers', finish: '' },
    { element_name: 'DJ Setup', finish: 'Controller + speakers' },
    { element_name: 'Background Music System', finish: '' },
  ],
  'Lighting': [
    { element_name: 'Stage Lighting', finish: 'Moving heads + wash lights' },
    { element_name: 'Ambient Lighting', finish: 'LED RGB uplighters' },
    { element_name: 'Follow Spot', finish: '1200W with operator' },
    { element_name: 'Truss Structure', finish: 'Aluminium box truss' },
    { element_name: 'Lighting Console', finish: 'DMX controller' },
    { element_name: 'Gobos / Patterns', finish: '' },
    { element_name: 'Fairy Lights / Decorative', finish: '' },
  ],
  'Video & LED': [
    { element_name: 'LED Video Wall', finish: 'P3.9 indoor panel' },
    { element_name: 'Projector & Screen', finish: '10,000 lumen, 16:9 screen' },
    { element_name: 'Video Switching Console', finish: '' },
    { element_name: 'Prompter / Teleprompter', finish: 'Glass teleprompter' },
    { element_name: 'Camera (IMAG)', finish: 'Live camera feed to screen' },
    { element_name: 'LED Riser Facia', finish: 'P4 or P5 outdoor panel' },
    { element_name: 'Confidence Monitor', finish: 'For speaker reference' },
  ],
  'Manpower': [
    { element_name: 'Event Manager (On-site)', finish: '' },
    { element_name: 'Assistant Event Manager', finish: '' },
    { element_name: 'Emcee / Anchor', finish: '' },
    { element_name: 'Female Hosts / Hostesses', finish: 'Formals attire' },
    { element_name: 'Registration Volunteers', finish: 'Branded t-shirts' },
    { element_name: 'Support Staff', finish: 'General duty' },
    { element_name: 'Security Personnel', finish: '' },
    { element_name: 'Electrician', finish: '' },
    { element_name: 'Carpenter / Fabrication Supervisor', finish: '' },
    { element_name: 'AV Technician', finish: '' },
  ],
  'Furniture': [
    { element_name: 'Chairs', finish: 'Banquet / theatre style' },
    { element_name: 'Tables', finish: 'Round / rectangular' },
    { element_name: 'High Tables (Cocktail)', finish: 'Bar height, draped' },
    { element_name: 'Sofa / Lounge Seating', finish: '' },
    { element_name: 'Registration Desk', finish: 'Skirted table' },
    { element_name: 'Lectern / Podium', finish: '' },
    { element_name: 'Display Tables', finish: 'Product display' },
  ],
  'Venue & Infrastructure': [
    { element_name: 'Venue Recce', finish: '' },
    { element_name: 'AC / Cooling Units', finish: '' },
    { element_name: 'Portable Toilets', finish: '' },
    { element_name: 'Tentage / Marquee', finish: 'Waterproof tent' },
    { element_name: 'Flooring', finish: 'Wooden / carpet / matting' },
    { element_name: 'Barricading', finish: 'MS crowd control barriers' },
    { element_name: 'Signage Poles / Standoffs', finish: '' },
  ],
  'Power & Electrical': [
    { element_name: 'Generator (DG Set)', finish: 'As per total load requirement' },
    { element_name: 'Generator Operator', finish: 'Per shift' },
    { element_name: 'Diesel / Fuel', finish: 'Billed on actuals' },
    { element_name: 'Power Distribution Board', finish: 'Main + sub DB' },
    { element_name: 'Cabling & Wiring', finish: 'As per layout' },
    { element_name: 'Cable Ramps / Covers', finish: 'Safety matting' },
    { element_name: 'Extension Boards / Sockets', finish: '' },
    { element_name: 'Electrician', finish: 'Per day' },
    { element_name: 'UPS / Inverter', finish: 'For critical equipment' },
    { element_name: 'Earthing Setup', finish: '' },
  ],
  'Venue Booking': [
    { element_name: 'Hall / Venue Rental', finish: '' },
    { element_name: 'Pre-function Area', finish: '' },
    { element_name: 'Green Room', finish: '' },
    { element_name: 'Parking Charges', finish: '' },
    { element_name: 'Hotel Rooms (Crew)', finish: '' },
  ],
  'Food & Beverage': [
    { element_name: 'Welcome Drink', finish: '' },
    { element_name: 'Tea / Coffee Station', finish: '' },
    { element_name: 'Lunch / Dinner', finish: '' },
    { element_name: 'High Tea / Snacks', finish: '' },
    { element_name: 'Water Bottles', finish: '' },
    { element_name: 'Cocktail / Mocktail Bar', finish: '' },
  ],
  'Travel Booking': [
    { element_name: 'Flight Tickets (Client Delegates)', finish: '' },
    { element_name: 'Train Tickets', finish: '' },
    { element_name: 'Airport Transfers', finish: '' },
    { element_name: 'Local Transport (Cab)', finish: '' },
    { element_name: 'Bus / Coach Hire', finish: '' },
    { element_name: 'Hotel Accommodation (Delegates)', finish: '' },
  ],
  'Logistics': [
    { element_name: 'Material Transportation (Truck)', finish: '' },
    { element_name: 'Loading / Unloading Labour', finish: '' },
    { element_name: 'Air Cargo / Courier', finish: '' },
    { element_name: 'Warehouse / Storage', finish: '' },
    { element_name: 'Packing Material', finish: '' },
  ],
  'Permissions & Legal': [
    { element_name: 'Police Permission', finish: '' },
    { element_name: 'Fire NOC', finish: '' },
    { element_name: 'Municipality Permission', finish: '' },
    { element_name: 'Entertainment License', finish: '' },
    { element_name: 'FSSAI License (F&B)', finish: '' },
    { element_name: 'Union Labour Permission', finish: '' },
    { element_name: 'Matadi / Local Body Charges', finish: '' },
  ],
  'Insurance': [
    { element_name: 'Event Liability Insurance', finish: '' },
    { element_name: 'Equipment Insurance', finish: '' },
    { element_name: 'Cancellation Cover', finish: '' },
  ],
  'Technology & IT': [
    { element_name: 'Event App / Registration Portal', finish: '' },
    { element_name: 'Wi-Fi / Internet Setup', finish: '' },
    { element_name: 'Tablets / iPads (Check-in)', finish: '' },
    { element_name: 'Photo Kiosk / Booth Software', finish: '' },
    { element_name: 'Livestreaming Setup', finish: '' },
    { element_name: 'QR Code / Badge Printing', finish: '' },
  ],
  'Gifts & Merchandise': [
    { element_name: 'Welcome Kit', finish: '' },
    { element_name: 'Trophy / Award', finish: '' },
    { element_name: 'Branded Merchandise', finish: '' },
    { element_name: 'Gift Hamper', finish: '' },
    { element_name: 'Certificate / Memento', finish: '' },
    { element_name: 'Bags / Tote Bags', finish: '' },
  ],
  'Photography & Videography': [
    { element_name: 'Event Photographer', finish: '' },
    { element_name: 'Videographer', finish: '' },
    { element_name: 'Drone Videography', finish: '' },
    { element_name: 'Live Streaming', finish: '' },
    { element_name: 'Post-production / Edit', finish: '' },
    { element_name: 'Photo Printing (Booth)', finish: '' },
  ],
  'Agency Cost': [
    { element_name: 'Agency Management Fee', finish: '' },
    { element_name: 'Agency Travel & Stay', finish: 'Billed on actuals' },
    { element_name: 'Creative / Design Fee', finish: '' },
    { element_name: 'Project Coordination', finish: '' },
  ],
  'Miscellaneous': [
    { element_name: 'Contingency', finish: '2-3% of total budget' },
    { element_name: 'Stationery', finish: '' },
    { element_name: 'First Aid / Medical', finish: '' },
    { element_name: 'Waste Management', finish: '' },
  ],
}
