import React, { useEffect } from "react";

/* ─────────────────────────────────────────────
   Myoozz Events — Terms of Use
   Brand: #bc1723 red · #FAFAF8 warm white
   Fonts: Cormorant Garamond (headlines) · DM Sans (body)
   Last updated: April 2026
   © Myoozz Consulting Pvt. Ltd.
───────────────────────────────────────────── */

const LAST_UPDATED = "April 2026";
const CONTACT_EMAIL = "legal@myoozz.events";
const COMPANY = "Myoozz Consulting Pvt. Ltd.";

const sections = [
  {
    id: "about",
    icon: "✦",
    title: "What Myoozz Events Is",
    body: [
      "Myoozz Events is a proprietary event planning and management platform developed, owned, and operated by Myoozz Consulting Pvt. Ltd., a company incorporated under the laws of India.",
      "This platform was built with a singular purpose: to simplify the life of event professionals — whether you are a seasoned planner who has spent years in spreadsheets, or someone stepping into your first event with limited experience but the drive to get it right.",
      "Myoozz Events acts as your system, your structure, and your guide — telling you what to do next so you can focus on execution.",
    ],
  },
  {
    id: "ownership",
    icon: "◈",
    title: "Ownership & Intellectual Property",
    body: [
      "Everything that makes Myoozz Events what it is — the software, design, workflows, document formats, logic, architecture, and all associated content — is the exclusive intellectual property of Myoozz Consulting Pvt. Ltd.",
      "This platform is protected under:",
      [
        "The Copyright Act, 1957 (India)",
        "The Information Technology Act, 2000 (India)",
        "Applicable international intellectual property treaties",
      ],
      "You may use Myoozz Events under the licence granted below. You may not copy, replicate, reverse-engineer, decompile, distribute, resell, or create derivative works from any part of this platform without express written permission from Myoozz Consulting Pvt. Ltd.",
    ],
  },
  {
    id: "licence",
    icon: "◎",
    title: "Your Licence to Use This Platform",
    body: [
      "By creating an account, you are granted a limited, personal, non-exclusive, non-transferable licence to access and use Myoozz Events during the period your account is active.",
      "This licence is granted to you — not to a third party, not to another organisation, and not for resale or redistribution.",
      [
        "You may use the platform to manage events for yourself or your organisation",
        "You may invite team members within your registered workspace",
        "You may generate, download, and use documents produced by the platform for your professional work",
      ],
      "Any use beyond this scope requires prior written approval from Myoozz Consulting Pvt. Ltd.",
    ],
  },
  {
    id: "yourdata",
    icon: "◉",
    title: "Your Data, Your Responsibility",
    body: [
      "Everything entered into Myoozz Events — vendor details, event budgets, team assignments, client briefs, timelines — is entered by you.",
      "The platform stores what you give it. It organises, surfaces, and suggests based on what you have built. But you remain responsible for the accuracy, completeness, and appropriateness of all data you input.",
      "Before acting on any document, proposal, cue sheet, or plan generated by this platform, you must review and verify it. The platform assists your judgement — it does not replace it.",
      "Myoozz Events will not be liable for decisions made on the basis of data that you entered incorrectly, incompletely, or without adequate review.",
    ],
  },
  {
    id: "disclaimer",
    icon: "◇",
    title: "Outcomes Are Yours",
    body: [
      "Myoozz Events is a tool. A powerful one — but a tool.",
      "Any outcome that results from using this platform — financial, operational, reputational, or otherwise — is the result of your decisions, your team's execution, and your client relationships. The platform does not control these. It supports them.",
      "If you use a budget projection generated on this platform and your margins shift — that is a business outcome. If a vendor you added to your database underperforms — that is an operational outcome. Neither of these is attributable to Myoozz Events or Myoozz Consulting Pvt. Ltd.",
      "Similarly, the successes you build using this platform are yours. Your efficiency gains, your client wins, your event outcomes — those belong to you.",
      "We make no guarantees of specific results. We do guarantee that we will keep building a platform worthy of your work.",
    ],
  },
  {
    id: "conduct",
    icon: "⬡",
    title: "How You Agree to Use This Platform",
    body: [
      "By using Myoozz Events, you agree to:",
      [
        "Provide accurate information during registration and throughout your use",
        "Keep your account credentials secure and not share access with unauthorised individuals",
        "Use the platform only for lawful event management purposes",
        "Not attempt to access, probe, or test the security of the platform",
        "Not upload content that is unlawful, defamatory, or harmful",
        "Not use the platform to misrepresent your identity or organisation to clients or vendors",
      ],
      "Violation of these terms may result in suspension or permanent deactivation of your account.",
    ],
  },
  {
    id: "beta",
    icon: "△",
    title: "Beta Access & Future Pricing",
    body: [
      "Myoozz Events is currently in its early access phase. During this period, the platform is available to you at no cost.",
      "We believe the planners who join early and shape this platform deserve to experience what they helped build — which is why we invite early adopters rather than rush a pricing model.",
      "When we move to a commercial model, you will be notified in advance — with enough time to make an informed decision. No surprises. No silent upgrades.",
      "Feature availability, access tiers, and terms of use may evolve as the platform matures. When material changes occur, we will communicate them clearly.",
    ],
  },
  {
    id: "termination",
    icon: "✕",
    title: "Pausing or Ending Your Account",
    body: [
      "You may stop using Myoozz Events at any time. Your data will remain archived and recoverable — because we practise soft delete across the entire platform.",
      "If you wish to permanently delete your account and all associated data, you may submit a written request to " + CONTACT_EMAIL + ". We will process it within 15 working days and confirm when it is done.",
      "We reserve the right to suspend or deactivate accounts that violate these terms, with or without prior notice depending on the severity of the breach.",
    ],
  },
  {
    id: "availability",
    icon: "⟳",
    title: "Platform Availability & Reporting Issues",
    body: [
      "Myoozz Events is provided on an \"as available\" basis, particularly during its early access phase. While we work to ensure the platform is stable and reliable, we cannot guarantee uninterrupted access or completely error-free operation at all times.",
      "If you encounter a technical issue — a calculation that looks wrong, a document that did not generate correctly, a feature behaving unexpectedly — we want to know immediately. Write to us at " + CONTACT_EMAIL + " with a brief description of what happened and we will investigate and respond promptly.",
      "You can also expect:",
      [
        "Planned maintenance to be communicated in advance wherever possible",
        "Critical bugs affecting your active events to be prioritised above all else",
        "A response to every reported issue — not silence",
      ],
      "Myoozz Consulting Pvt. Ltd. will not be liable for losses, delays, or disruptions arising from technical faults, planned maintenance, or circumstances beyond our reasonable control. However, we commit to taking every reported issue seriously and resolving it as quickly as possible.",
      "Your work matters. When something breaks, tell us — and we will fix it.",
    ],
  },
  {
    id: "law",
    icon: "⚖",
    title: "Governing Law & Jurisdiction",
    body: [
      "These Terms of Use are governed by the laws of India.",
      "Any disputes arising from or related to the use of this platform shall be subject to the exclusive jurisdiction of the courts at the registered office of Myoozz Consulting Pvt. Ltd.",
      "If any provision of these terms is found to be unenforceable, the remaining provisions continue in full force.",
    ],
  },
  {
    id: "contact",
    icon: "✉",
    title: "Questions & Legal Correspondence",
    body: [
      "For questions about these terms, licensing enquiries, or legal correspondence, write to:",
      CONTACT_EMAIL,
      "Myoozz Consulting Pvt. Ltd. · Registered Office, India",
      "We aim to respond to all legal queries within 10 working days.",
    ],
  },
];

export default function TermsOfUse() {
  useEffect(() => {
    window.scrollTo(0, 0);
  }, []);

  return (
    <>
      <style>{`
        @import url('https://fonts.googleapis.com/css2?family=Cormorant+Garamond:ital,wght@0,400;0,500;0,600;1,400;1,500&family=DM+Sans:wght@300;400;500&display=swap');

        :root {
          --red: #bc1723;
          --bg: #FAFAF8;
          --ink: #1a1a1a;
          --muted: #6b6b6b;
          --rule: #e8e4df;
          --card: #ffffff;
        }

        .tu-root * { box-sizing: border-box; margin: 0; padding: 0; }

        .tu-root {
          background: var(--bg);
          color: var(--ink);
          font-family: 'DM Sans', sans-serif;
          font-weight: 300;
          min-height: 100vh;
        }

        /* ── Nav ── */
        .tu-nav {
          display: flex;
          align-items: center;
          justify-content: space-between;
          padding: 20px 36px;
          background: var(--bg);
          border-bottom: 1px solid var(--rule);
          position: sticky;
          top: 0;
          z-index: 100;
        }
        .tu-logo {
          display: flex;
          align-items: center;
          gap: 10px;
          text-decoration: none;
        }
        .tu-logo-me {
          font-family: 'Poppins', 'DM Sans', sans-serif;
          font-size: 15px;
          font-weight: 700;
          color: #fff;
          background: var(--red);
          width: 34px; height: 34px;
          display: flex; align-items: center; justify-content: center;
          border-radius: 4px;
          letter-spacing: 0.02em;
        }
        .tu-logo-text {
          font-family: 'DM Sans', sans-serif;
          font-size: 14px;
          font-weight: 400;
          color: var(--ink);
          letter-spacing: 0.01em;
        }
        .tu-logo-text em {
          font-style: normal;
          color: var(--red);
          margin-left: 2px;
        }
        .tu-nav-link {
          font-size: 13px;
          font-weight: 400;
          color: var(--muted);
          text-decoration: none;
          letter-spacing: 0.02em;
        }
        .tu-nav-link:hover { color: var(--red); }

        /* ── Hero ── */
        .tu-hero {
          background: var(--bg);
          border-bottom: 1px solid var(--rule);
          padding: 80px 24px 60px;
          text-align: center;
          position: relative;
          overflow: hidden;
        }
        .tu-hero::before {
          content: '';
          position: absolute;
          top: -60px; left: 50%;
          transform: translateX(-50%);
          width: 320px; height: 320px;
          background: radial-gradient(circle, rgba(188,23,35,0.06) 0%, transparent 70%);
          pointer-events: none;
        }
        .tu-tag {
          display: inline-block;
          font-family: 'DM Sans', sans-serif;
          font-size: 11px;
          font-weight: 500;
          letter-spacing: 0.18em;
          text-transform: uppercase;
          color: var(--red);
          border: 1px solid rgba(188,23,35,0.25);
          border-radius: 2px;
          padding: 5px 14px;
          margin-bottom: 28px;
        }
        .tu-hero h1 {
          font-family: 'Cormorant Garamond', serif;
          font-size: clamp(40px, 6vw, 68px);
          font-weight: 500;
          line-height: 1.05;
          letter-spacing: -0.01em;
          color: var(--ink);
          max-width: 700px;
          margin: 0 auto 20px;
        }
        .tu-hero h1 em {
          font-style: italic;
          color: var(--red);
        }
        .tu-hero-sub {
          font-size: 15px;
          font-weight: 300;
          color: var(--muted);
          line-height: 1.7;
          max-width: 540px;
          margin: 0 auto 28px;
        }
        .tu-meta {
          font-size: 12px;
          color: var(--muted);
          letter-spacing: 0.04em;
        }

        /* ── Important notice banner ── */
        .tu-notice {
          background: rgba(188,23,35,0.04);
          border-left: 3px solid var(--red);
          padding: 18px 28px;
          margin: 40px auto 0;
          max-width: 820px;
          border-radius: 0 4px 4px 0;
        }
        .tu-notice p {
          font-size: 13.5px;
          font-weight: 400;
          color: #444;
          line-height: 1.7;
        }
        .tu-notice strong {
          color: var(--red);
          font-weight: 500;
        }

        /* ── Layout ── */
        .tu-layout {
          max-width: 820px;
          margin: 0 auto;
          padding: 56px 24px 100px;
        }

        /* ── Section ── */
        .tu-section {
          display: grid;
          grid-template-columns: 48px 1fr;
          gap: 0 28px;
          padding: 48px 0;
          border-bottom: 1px solid var(--rule);
        }
        .tu-section:last-child { border-bottom: none; }

        .tu-section-icon {
          padding-top: 6px;
          font-size: 18px;
          color: var(--red);
          opacity: 0.7;
          line-height: 1;
        }

        .tu-section h2 {
          font-family: 'Cormorant Garamond', serif;
          font-size: clamp(22px, 3vw, 30px);
          font-weight: 500;
          color: var(--ink);
          line-height: 1.2;
          margin-bottom: 20px;
        }

        .tu-section p {
          font-size: 15px;
          font-weight: 300;
          line-height: 1.8;
          color: #333;
          margin-bottom: 14px;
        }
        .tu-section p:last-child { margin-bottom: 0; }

        .tu-section p.tu-email {
          font-family: 'DM Sans', sans-serif;
          font-weight: 400;
          font-size: 14px;
          color: var(--red);
          letter-spacing: 0.01em;
        }

        .tu-section ul {
          list-style: none;
          padding: 0;
          margin: 4px 0 14px;
        }
        .tu-section ul li {
          font-size: 14.5px;
          font-weight: 300;
          line-height: 1.75;
          color: #444;
          padding-left: 20px;
          position: relative;
          margin-bottom: 4px;
        }
        .tu-section ul li::before {
          content: '—';
          position: absolute;
          left: 0;
          color: var(--red);
          font-weight: 400;
        }

        /* ── Footer strip ── */
        .tu-footer-strip {
          background: var(--ink);
          color: rgba(255,255,255,0.5);
          text-align: center;
          padding: 28px 24px;
          font-size: 12.5px;
          font-weight: 300;
          letter-spacing: 0.03em;
          line-height: 1.8;
        }
        .tu-footer-strip a {
          color: rgba(188,23,35,0.8);
          text-decoration: none;
        }
        .tu-footer-strip a:hover { color: var(--red); }

        @media (max-width: 600px) {
          .tu-section {
            grid-template-columns: 1fr;
            gap: 12px 0;
          }
          .tu-section-icon { display: none; }
          .tu-nav { padding: 16px 20px; }
        }
      `}</style>

      <div className="tu-root">
        {/* ── Logo Nav ── */}
        <nav className="tu-nav">
          <a href="/" className="tu-logo" aria-label="Myoozz Events Home">
            <span className="tu-logo-me">ME</span>
            <span className="tu-logo-text">Myoozz<em>Events</em></span>
          </a>
          <a href="/privacy" className="tu-nav-link">Privacy Policy</a>
        </nav>

        {/* ── Hero ── */}
        <div className="tu-hero">
          <div className="tu-tag">Myoozz Events · Terms of Use</div>
          <h1>Built for you.<br /><em>Used by you.</em></h1>
          <p className="tu-hero-sub">
            These terms exist to protect you, your work, and this platform.
            They are written to be read — not buried.
          </p>
          <p className="tu-meta">Last updated: {LAST_UPDATED} · {COMPANY}</p>
        </div>

        {/* ── Notice Banner ── */}
        <div className="tu-layout" style={{ paddingBottom: 0, paddingTop: 40 }}>
          <div className="tu-notice">
            <p>
              <strong>By using Myoozz Events, you agree to these terms.</strong> If you are
              registering on behalf of an organisation, you confirm that you have the authority
              to bind that organisation to these terms.
            </p>
          </div>
        </div>

        {/* ── Sections ── */}
        <div className="tu-layout">
          {sections.map((s) => (
            <div className="tu-section" key={s.id} id={s.id}>
              <div className="tu-section-icon">{s.icon}</div>
              <div>
                <h2>{s.title}</h2>
                {s.body.map((block, i) =>
                  Array.isArray(block) ? (
                    <ul key={i}>
                      {block.map((item, j) => (
                        <li key={j}>{item}</li>
                      ))}
                    </ul>
                  ) : block === CONTACT_EMAIL ? (
                    <p key={i} className="tu-email">
                      <a href={`mailto:${CONTACT_EMAIL}`} style={{ color: "inherit" }}>
                        {CONTACT_EMAIL}
                      </a>
                    </p>
                  ) : (
                    <p key={i}>{block}</p>
                  )
                )}
              </div>
            </div>
          ))}
        </div>

        {/* ── Bottom strip ── */}
        <div className="tu-footer-strip">
          © {new Date().getFullYear()} {COMPANY}. All rights reserved.
          Protected under the Copyright Act, 1957 &amp; IT Act, 2000.<br />
          Questions? Write to{" "}
          <a href={`mailto:${CONTACT_EMAIL}`}>{CONTACT_EMAIL}</a>
          &nbsp;·&nbsp;
          <a href="/privacy">Privacy Policy</a>
        </div>
      </div>
    </>
  );
}
